mode: "pairwise" # separate, or pairwise

#shared
jcpu: 8
jgpu: 1
jmem: 36
jwalltime: "12:00:00"
library_path: "/beacon-projects/hp_ppi/libraries/protein/fasta"

#mode specific
separate:
  keys: "transcript"
  # species name matching library filename
  species: "hg38_115"
  #input file name
  idfile: "inputs/mdm2.txt"

pairwise:
  # key names in the format "key1:key2"
  keys: "transcript:transcript"
  # species names matching library filename in the format "species1:species2"
  species: "hg38_115:hg38_115"
  # input file names
  idfile1: "inputs/hsapiens_known_interactors1.txt"
  idfile2: "inputs/hsapiens_known_interactors2.txt"
  # optional, if empty, it will use the libpath instead.
  # use if two species have different library paths.
  species1_libpath: ""
  species2_libpath: ""